name 'rabbitmq-cluster'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures a RabbitMQ cluster.'
long_description 'Application cookbook which installs and configures a RabbitMQ cluster.'
version '2.0.0'

depends 'chef-vault'
depends 'erlang'
depends 'poise', '~> 2.0'
depends 'poise-service'
depends 'ulimit'

supports 'ubuntu', '>= 12.04'
supports 'redhat', '>= 6.4'
supports 'centos', '>= 6.4'
