name 'rabbitmq-cluster'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Installs and configures RabbitMQ cluster.'
long_description 'Installs and configures RabbitMQ cluster.'
version '1.1.1'

depends 'poise', '~> 2.0'
depends 'poise-service'
depends 'rabbitmq', '= 3.13.0'

supports 'ubuntu', '>= 12.04'
supports 'redhat', '>= 6.4'
supports 'centos', '>= 6.4'
